name: demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  provider: ^2.0.1
  image_picker: ^0.6.0+3
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  starflut: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/smile.png
    - assets/icontexto-emoticons-01.ico
  #  - images/a_dot_ham.jpeg
